[window]
padding.x = 10
padding.y = 10

opacity = 0.9
blur = true

[font]
size = 13

[colors]
[colors.primary]
background = "#282a36"  # Dracula theme background color
foreground = "#f8f8f2"  # Dracula theme foreground color

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92d0"
cyan = "#a4ffff"
white = "#ffffff"

